-- NOTE: This file is auto generated by ./sql-generator

-- WorkflowRepository.search
select
  *,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "workflow_step"
        where
          "workflow_step"."workflowId" = "workflow"."id"
      ) as agg
  ) as "steps"
from
  "workflow"
order by
  "createdAt" desc

-- WorkflowRepository.get
select
  *,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          *
        from
          "workflow_step"
        where
          "workflow_step"."workflowId" = "workflow"."id"
      ) as agg
  ) as "steps"
from
  "workflow"
where
  "id" = $1

-- WorkflowRepository.getForWorkflowRun
select
  "workflow"."id",
  "workflow"."name",
  "workflow"."trigger",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "workflow_step"."id",
          "workflow_step"."config",
          "plugin_method"."pluginId" as "pluginId",
          "plugin_method"."name" as "methodName",
          "plugin_method"."types" as "types"
        from
          "workflow_step"
          inner join "plugin_method" on "plugin_method"."id" = "workflow_step"."pluginMethodId"
        where
          "workflow_step"."workflowId" = "workflow"."id"
          and "workflow_step"."enabled" = $1
      ) as agg
  ) as "steps"
from
  "workflow"
where
  "id" = $2
  and "enabled" = $3

-- WorkflowRepository.delete
delete from "workflow"
where
  "id" = $1

-- WorkflowRepository.getSteps
select
  *
from
  "workflow_step"
where
  "workflowId" = $1
order by
  "order" asc

-- WorkflowRepository.deleteStep
delete from "workflow_step"
where
  "workflowId" = $1
  and "id" = $2
